apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-nginx
spec: 
  replicas: 3
  selector:
    matchLabels:
      app: desafio-nginx
  template:
    metadata:
      labels:
        app: desafio-nginx      
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            readOnly: true
            name: nginx-conf        
      
      volumes:
      - name: nginx-conf
        configMap: 
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf